title: Conference Deadlines
description: Countdowns to conferences that I care about.
author: Vito C.H. Wu

domain: "Vito-Swift.github.io"
baseurl: ""

twitter_username: Vito_CWu
github_username: Vito-Swift
github_repo: Vito-Swift.github.io

markdown: kramdown

