title: Conference Deadlines
description: Countdowns to conference that I care about.
author: Vito C.H. Wu

domain: "Vito-Swift.github.io"
baseurl: ""

twitter_username: Vito_CWu
github_username: Vito-Swift
github_repo: Vito-Swift

markdown: kramdown

